name: Deploy Test API

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check the current user
        run: |
          whoami

      - name: Build Test API Docker image
        run: |
          docker build -t test_api_image .

      - name: Deploy Test API
        run: |
          docker stop test_api_container || true
          docker rm test_api_container || true
          docker run -d \
          -e PORT=${{ env.API_PORT }} \
          -e NODE_ENV=${{ env.API_NODE_ENV }} \
          -e MONGO_URI=${{ secrets.MONGO_URI }} \
          -e JWT_SECRET=${{ secrets.API_JWT_SECRET }} \
          -e GMAIL_USERNAME=${{secrets.GMAIL_USERNAME}} \
          -e GMAIL_PASSWORD=${{secrets.GMAIL_PASSWORD}} \
          --name test_api_container \
          -p 8000:8000 \
          test_api_image:latest

      - name: Remove Dangling Docker images
        run: |
          docker rmi $(docker images --quiet --filter "dangling=true") || true
